import random
from telegram.ext import CommandHandler, ContextTypes
from telegram import Update

class VerdadReto:
    def __init__(self):
        self.verdad_reto_command = CommandHandler("vrddoreto", self.verdadoreto)

    async def verdadoreto(self, update: Update, context: ContextTypes.DEFAULT_TYPE):
        verdad = ["¿Cuál ha sido tu mayor vergüenza?", "¿Alguna vez mentiste a un amigo cercano?", "¿Cuál es tu secreto más oscuro?", "¿Has stalkeado a alguien en redes sociales?", "¿A quién has espiado en secreto?", "¿Has llorado por amor?", "¿Alguna vez te enamoraste de alguien prohibido?", "¿Qué es lo más ilegal que has hecho?", "¿Tienes alguna fobia rara?", "¿Qué hábito vergonzoso tienes en privado?", "¿Has tenido un amor no correspondido?", "¿Alguna vez engañaste en un examen?", "¿Has mentido sobre tu edad?", "¿Cuál es tu peor cita?", "¿Tienes un crush secreto?", "¿Has enviado un mensaje por error a la persona equivocada?", "¿Has fingido estar enfermo para no salir?", "¿Qué es lo más infantil que todavía haces?", "¿Alguna vez hablaste mal de un amigo a sus espaldas?", "¿Te has enamorado de alguien por internet?", "¿Qué es lo más inmaduro que has hecho en una relación?", "¿Qué mentira blanca dices seguido?", "¿Has tenido un sueño extraño con alguien conocido?", "¿Alguna vez te gustó el novio o novia de un amigo?", "¿Te has sentido atraído por alguien del mismo sexo?", "¿Has sido infiel o te han sido infiel?", "¿Qué rumor has difundido sin saber si era verdad?", "¿Alguna vez te hiciste el dormido para evitar a alguien?", "¿Tienes alguna cuenta secreta en redes sociales?", "¿Te arrepientes de haber conocido a alguien?", "¿Cuál fue tu peor metida de pata?", "¿Alguna vez te avergonzaste de tu familia?", "¿Tienes alguna obsesión secreta?", "¿Te gustaría cambiar de vida con alguien?", "¿Qué es lo más ridículo que has hecho por amor?", "¿Alguna vez tuviste una doble vida (en secreto)?", "¿Has dicho 'te amo' sin sentirlo realmente?", "¿Cuál es tu mayor inseguridad?", "¿Te has sentido solo aunque estuvieras rodeado de gente?", "¿Tienes una fantasía que nunca contarías?"]
        reto = ["Reta a alguien a hacer 10 flexiones ahora mismo", "Envía un mensaje vergonzoso al último contacto de tu lista", "Baila sin música durante un minuto", "Imita a tu personaje de película favorito", "Cuenta un secreto que nunca hayas contado antes", "Haz una llamada y canta una canción completa", "Publica una foto graciosa en tu estado", "Come una cucharada de algo picante", "Haz una imitación de alguien del grupo", "Envía un mensaje a tu crush diciendo que te gusta", "Haz una pose ridícula y toma una foto", "Corre en el lugar durante dos minutos sin parar", "Haz sonidos de animales durante 30 segundos", "Habla con acento extranjero por cinco minutos", "Envía un mensaje diciendo 'Te extraño' a alguien inesperado", "Cuenta un chiste muy malo", "Haz un dibujo en menos de un minuto y muéstralo", "Salta en un pie durante un minuto", "Cambia tu foto de perfil por una divertida por una hora", "Imita a un cantante famoso", "Llama a alguien y dile que ganaste la lotería", "Esconde algo en la habitación y dile a alguien que lo busque", "Haz una declaración de amor a un objeto inanimado", "Di el abecedario al revés", "Haz un video haciendo un baile tonto y envíalo", "Envía un mensaje con solo emojis y que alguien lo interprete", "Cuenta una anécdota embarazosa", "Haz una carrera de 10 metros en tu casa", "Intenta tocarte la nariz con la lengua", "Haz un sonido de risa muy raro", "Haz una pose de superhéroe y quédate así por un minuto", "Envía un mensaje diciendo que tienes un talento oculto", "Actúa como un robot durante cinco minutos", "Haz un brindis imaginario y dilo en voz alta", "Canta el himno nacional", "Habla en rima durante cinco minutos", "Haz una foto con cara de sorpresa y envíala", "Baila como si nadie te estuviera viendo", "Imita a un animal y que los demás adivinen cuál es"]
        eleccion = random.choice(["verdad", "reto"])
        contenido = random.choice(verdad if eleccion == "verdad" else reto)
        await update.message.reply_text(f"👉 *{eleccion.upper()}*: {contenido}", parse_mode="Markdown", reply_to_message_id=update.message.message_id)
        print("CMD | Comando /vrddoreto ejecutado.")

def setup():
    return VerdadReto()